# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c427a7c96fd9c0482bec7174825cf292d6407391c39d1f7f358fd9b206375d17709639a2625b4909ba3bdeee8736963332b2ff7be1005394036aa4def34bf5cc

test:
  secret_key_base: 78e02e1de7a8a3877e2fd24126f80d7074e994e5dc02197340a50640d4a6e1ef086fa4dc50caf708c1079f4f41338f33a66bad3dc4e1a386fd79f8077292da3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
